import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "mr" | "ta" | "te" | "pa";
type FontScale = "small" | "medium" | "large" | "xl";

interface AppSettings {
  darkMode: boolean;
  elderlyMode: boolean;
  language: Language;
  fontScale: FontScale;
  setDarkMode: (v: boolean) => void;
  setElderlyMode: (v: boolean) => void;
  setLanguage: (v: Language) => void;
  setFontScale: (v: FontScale) => void;
  t: (key: string) => string;
  simplify: (str: string) => string;
}

const jargonMap: Record<string, string> = {
  "otp": "One-Time Secret Password (OTP)",
  "url": "Blue Web Link",
  "urls": "Blue Web Links",
  "phishing": "Fake Website Trap",
  "deepfakes": "AI-Generated Fakes",
  "deepfake": "AI-Generated Fake",
  "sms": "Text Message",
  "scammer": "fraudster",
  "apk": "App File",
};

const replaceJargon = (str: string, elderly: boolean) => {
  if (!elderly || typeof str !== "string") return str;
  let s = str;
  Object.entries(jargonMap).forEach(([jargon, simple]) => {
     s = s.replace(new RegExp(`\\b${jargon}\\b`, "gi"), simple);
  });
  return s;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "DigiRakshak",
    "app.tagline": "AI-Powered Cyber Safety",
    "hero.title1": "Stay Safe in the",
    "hero.title2": "Digital World",
    "hero.subtitle": "DigiRakshak helps you identify scam calls, suspicious messages, and learn cyber safety — all powered by AI.",
    "card.call.title": "Check a Call",
    "card.call.desc": "Verify if an incoming call is from a scammer or a legitimate source.",
    "card.message.title": "Check a Message",
    "card.message.desc": "Paste any suspicious SMS or WhatsApp message to detect fraud instantly.",
    "card.game.title": "Learn via Game",
    "card.game.desc": "Play fun interactive quizzes to learn how to protect yourself online.",
    "card.sandbox.title": "Safety Simulators",
    "card.sandbox.desc": "Practice identifying scams inside a safe simulated environment.",
    "card.upi.title": "UPI Training",
    "card.upi.desc": "Learn how to use UPI safely with step-by-step guided practice.",
    "card.scamy.title": "Scam Simulator",
    "card.scamy.desc": "Chat with Scamy, a fake scammer, and learn to resist tricks.",
    "card.progress.title": "Family & Rakhi",
    "card.progress.desc": "View your Digital Rakhi promise and unlock family memory rewards.",
    "card.cta": "Start",
    "hero.meet": "Meet Meena Didi — your digital safety guide!",
    "nav.quiz": "Quiz",
    "nav.sandbox": "Simulators",
    "nav.scamy": "Scamy",
    "nav.badges": "Badges",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.help": "Help",
    "settings.elderly": "Elderly Mode",
    "settings.dark": "Dark Mode",
    "settings.font": "Font Size",
    "chatur.name": "Chatur",
    "chatur.role": "Your Safety Assistant",
    "chatur.greeting": "Hi! I'm Chatur 🛡️ Your digital safety buddy. Ask me anything about staying safe online!",
    "chatur.placeholder": "Ask about cyber safety...",
    "chatur.listening": "Listening...",
    "chatur.processing": "Processing...",
    "font.small": "S",
    "font.medium": "M",
    "font.large": "L",
    "font.xl": "XL",
    "trust.scams": "Scams Detected",
    "trust.users": "Users Protected",
    "trust.tips": "Safety Tips Shared",
    "game.title": "Safe or Scam?",
    "game.subtitle": "Test your cyber safety knowledge with real-life scenarios",
    "game.safe": "Safe ✅",
    "game.scam": "Scam ❌",
    "game.correct": "Correct! 👍",
    "game.wrong": "Be careful next time ⚠️",
    "game.next": "Next Question",
    "game.restart": "Play Again",
    "game.score": "Your Score",
    "game.back": "Back to Home",
    "game.whatToDo": "What to do",
    "game.level": "Level",
    "upi.title": "UPI Safety Training",
    "upi.subtitle": "Learn to use UPI safely with this step-by-step guide",
    "upi.step": "Step",
    "upi.next": "Next Step",
    "upi.prev": "Previous",
    "upi.finish": "Finish Training",
    "upi.back": "Back to Home",
    "upi.complete": "Training Complete! 🎉",
    "upi.completeDesc": "You now know how to use UPI safely. Remember these tips!",
    "card.deepfake.title": "RealityCheck Lab",
    "card.deepfake.desc": "Spot AI-generated images or audio using side-by-side comparisons.",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
    "lang.mr": "मराठी",
    "lang.ta": "தமிழ்",
    "lang.te": "తెలుగు",
    "lang.pa": "ਪੰਜਾਬੀ",
  },
  hi: {
    "app.name": "DigiRakshak",
    "app.tagline": "AI-संचालित साइबर सुरक्षा",
    "hero.title1": "डिजिटल दुनिया में",
    "hero.title2": "सुरक्षित रहें",
    "hero.subtitle": "DigiRakshak आपको स्कैम कॉल, संदिग्ध संदेशों की पहचान करने और साइबर सुरक्षा सीखने में मदद करता है।",
    "card.call.title": "कॉल जांचें",
    "card.call.desc": "जांचें कि कोई इनकमिंग कॉल स्कैमर की है या वैध स्रोत की।",
    "card.message.title": "संदेश जांचें",
    "card.message.desc": "किसी भी संदिग्ध SMS या WhatsApp संदेश को पेस्ट करके तुरंत धोखाधड़ी का पता लगाएं।",
    "card.game.title": "गेम से सीखें",
    "card.game.desc": "मजेदार इंटरैक्टिव क्विज़ खेलकर ऑनलाइन सुरक्षा सीखें।",
    "card.sandbox.title": "सुरक्षा सिमुलेटर्स",
    "card.sandbox.desc": "एक सुरक्षित सिमुलेटेड वातावरण में स्कैम पहचानने का अभ्यास करें।",
    "card.upi.title": "UPI प्रशिक्षण",
    "card.upi.desc": "चरण-दर-चरण मार्गदर्शन से UPI का सुरक्षित उपयोग सीखें।",
    "card.scamy.title": "स्कैम सिमुलेटर",
    "card.scamy.desc": "Scamy नकली scammer से बात करें और tricks से बचना सीखें।",
    "card.progress.title": "राखी और परिवार",
    "card.progress.desc": "डिजिटल राखी का वादा देखें और पारिवारिक यादें अनलॉक करें।",
    "card.cta": "शुरू करें",
    "hero.meet": "मिलिए मीना दीदी से — आपकी डिजिटल safety guide!",
    "nav.quiz": "क्विज़",
    "nav.sandbox": "सिम्युलेटर",
    "nav.scamy": "Scamy",
    "nav.badges": "Badges",
    "nav.home": "होम",
    "nav.about": "हमारे बारे में",
    "nav.help": "मदद",
    "settings.elderly": "बुजुर्ग मोड",
    "settings.dark": "डार्क मोड",
    "settings.font": "फ़ॉन्ट आकार",
    "chatur.name": "चतुर",
    "chatur.role": "आपका सुरक्षा सहायक",
    "chatur.greeting": "नमस्ते! मैं चतुर हूँ 🛡️ आपका डिजिटल सुरक्षा साथी। ऑनलाइन सुरक्षा के बारे में कुछ भी पूछें!",
    "chatur.placeholder": "साइबर सुरक्षा के बारे में पूछें...",
    "chatur.listening": "सुन रहा हूँ...",
    "chatur.processing": "प्रोसेसिंग...",
    "font.small": "छो",
    "font.medium": "म",
    "font.large": "बड़",
    "font.xl": "XL",
    "trust.scams": "स्कैम पकड़े गए",
    "trust.users": "उपयोगकर्ता सुरक्षित",
    "trust.tips": "सुरक्षा टिप्स साझा",
    "game.title": "सेफ़ या स्कैम?",
    "game.subtitle": "वास्तविक परिदृश्यों से अपने साइबर सुरक्षा ज्ञान का परीक्षण करें",
    "game.safe": "सुरक्षित ✅",
    "game.scam": "स्कैम ❌",
    "game.correct": "सही! 👍",
    "game.wrong": "अगली बार सावधान रहें ⚠️",
    "game.next": "अगला सवाल",
    "game.restart": "फिर से खेलें",
    "game.score": "आपका स्कोर",
    "game.back": "होम पर वापस",
    "game.whatToDo": "क्या करें",
    "game.level": "लेवल",
    "upi.title": "UPI सुरक्षा प्रशिक्षण",
    "upi.subtitle": "इस चरण-दर-चरण गाइड से UPI का सुरक्षित उपयोग सीखें",
    "upi.step": "चरण",
    "upi.next": "अगला चरण",
    "upi.prev": "पिछला",
    "upi.finish": "प्रशिक्षण पूरा करें",
    "upi.back": "होम पर वापस",
    "upi.complete": "प्रशिक्षण पूरा! 🎉",
    "upi.completeDesc": "अब आप UPI सुरक्षित रूप से उपयोग करना जानते हैं। इन टिप्स को याद रखें!",
    "card.deepfake.title": "RealityCheck लैब",
    "card.deepfake.desc": "तस्वीरों या ऑडियो की तुलना करके AI-जनित नकली छवियों या आवाज़ को पहचानें।",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
    "lang.mr": "मराठी",
    "lang.ta": "தமிழ்",
    "lang.te": "తెలుగు",
    "lang.pa": "ਪੰਜਾਬੀ",
  },
  mr: {
    "app.name": "DigiRakshak",
    "app.tagline": "AI-चालित सायबर सुरक्षा",
    "hero.title1": "डिजिटल जगात",
    "hero.title2": "सुरक्षित रहा",
    "hero.subtitle": "DigiRakshak तुम्हाला स्कॅम कॉल, संशयास्पद संदेश ओळखण्यात आणि सायबर सुरक्षा शिकण्यात मदत करतो.",
    "card.call.title": "कॉल तपासा",
    "card.call.desc": "येणारा कॉल स्कॅमरचा आहे की वैध स्रोताचा ते तपासा.",
    "card.message.title": "संदेश तपासा",
    "card.message.desc": "कोणताही संशयास्पद SMS किंवा WhatsApp संदेश पेस्ट करा.",
    "card.game.title": "गेमने शिका",
    "card.game.desc": "मजेदार क्विझ खेळून ऑनलाइन सुरक्षा शिका.",
    "card.sandbox.title": "सुरक्षा सिमुलेटर्स",
    "card.sandbox.desc": "एका सुरक्षित सिम्युलेटेड वातावरणात स्कॅम ओळखण्याचा सराव करा.",
    "card.upi.title": "UPI प्रशिक्षण",
    "card.upi.desc": "चरण-दर-चरण मार्गदर्शनाने UPI सुरक्षितपणे वापरायला शिका.",
    "card.scamy.title": "स्कॅम सिम्युलेटर",
    "card.scamy.desc": "Scamy बनावट scammer शी बोला आणि युक्त्या टाळायला शिका।",
    "card.progress.title": "राखी आणि कुटुंब",
    "card.progress.desc": "डिजिटल राखीचे वचन पहा आणि कुटुंबाच्या आठवणी अनलॉक करा.",
    "card.cta": "सुरू करा",
    "hero.meet": "भेटा मीना दीदीला — तुमची डिजिटल safety मार्गदर्शक!",
    "nav.quiz": "क्विझ",
    "nav.sandbox": "सिम्युलेटर",
    "nav.scamy": "Scamy",
    "nav.badges": "Badges",
    "nav.home": "होम",
    "nav.about": "आमच्याबद्दल",
    "nav.help": "मदत",
    "settings.elderly": "ज्येष्ठ मोड",
    "settings.dark": "डार्क मोड",
    "settings.font": "फॉन्ट आकार",
    "chatur.name": "चतुर",
    "chatur.role": "तुमचा सुरक्षा सहाय्यक",
    "chatur.greeting": "नमस्कार! मी चतुर आहे 🛡️ तुमचा डिजिटल सुरक्षा साथीदार.",
    "chatur.placeholder": "सायबर सुरक्षेबद्दल विचारा...",
    "chatur.listening": "ऐकत आहे...",
    "chatur.processing": "प्रक्रिया करत आहे...",
    "font.small": "ला",
    "font.medium": "म",
    "font.large": "मो",
    "font.xl": "XL",
    "trust.scams": "स्कॅम पकडले",
    "trust.users": "वापरकर्ते सुरक्षित",
    "trust.tips": "सुरक्षा टिप्स शेअर",
    "game.title": "सेफ की स्कॅम?",
    "game.subtitle": "वास्तविक परिस्थितींमधून तुमचे सायबर सुरक्षा ज्ञान तपासा",
    "game.safe": "सुरक्षित ✅",
    "game.scam": "स्कॅम ❌",
    "game.correct": "बरोबर! 👍",
    "game.wrong": "पुढच्या वेळी सावधगिरी बाळगा ⚠️",
    "game.next": "पुढचा प्रश्न",
    "game.restart": "पुन्हा खेळा",
    "game.score": "तुमचा स्कोर",
    "game.back": "होम वर परत",
    "game.whatToDo": "काय करावे",
    "game.level": "लेव्हल",
    "upi.title": "UPI सुरक्षा प्रशिक्षण",
    "upi.subtitle": "या चरण-दर-चरण मार्गदर्शकाने UPI सुरक्षितपणे वापरायला शिका",
    "upi.step": "चरण",
    "upi.next": "पुढचे चरण",
    "upi.prev": "मागील",
    "upi.finish": "प्रशिक्षण पूर्ण करा",
    "upi.back": "होम वर परत",
    "upi.complete": "प्रशिक्षण पूर्ण! 🎉",
    "upi.completeDesc": "आता तुम्हाला UPI सुरक्षितपणे वापरता येतो. या टिप्स लक्षात ठेवा!",
    "card.deepfake.title": "RealityCheck लॅब",
    "card.deepfake.desc": "चित्रे किंवा ऑडिओची तुलना करून AI-निर्मित बनावट चित्रे किंवा आवाज ओळखा.",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
    "lang.mr": "मराठी",
    "lang.ta": "தமிழ்",
    "lang.te": "తెలుగు",
    "lang.pa": "ਪੰਜਾਬੀ",
  },
  ta: {
    "app.name": "DigiRakshak",
    "app.tagline": "AI-இயங்கும் சைபர் பாதுகாப்பு",
    "hero.title1": "டிஜிட்டல் உலகில்",
    "hero.title2": "பாதுகாப்பாக இருங்கள்",
    "hero.subtitle": "DigiRakshak மோசடி அழைப்புகள், சந்தேகத்திற்கிடமான செய்திகளை கண்டறிய உதவுகிறது.",
    "card.call.title": "அழைப்பை சரிபார்",
    "card.call.desc": "வரும் அழைப்பு மோசடியா அல்லது உண்மையானதா என்று சரிபார்க்கவும்.",
    "card.message.title": "செய்தியை சரிபார்",
    "card.message.desc": "சந்தேகத்திற்கிடமான SMS அல்லது WhatsApp செய்தியை ஒட்டவும்.",
    "card.game.title": "விளையாட்டு மூலம் கற்க",
    "card.game.desc": "வேடிக்கையான வினாடி வினா விளையாடி ஆன்லைன் பாதுகாப்பை கற்றுக்கொள்ளுங்கள்.",
    "card.sandbox.title": "பாதுகாப்பு சிமுலேட்டர்கள்",
    "card.sandbox.desc": "ஒரு பாதுகாப்பான சிமுலேட்டட் சூழலில் மோசடிகளை அடையாளம் காண பயிற்சி செய்யுங்கள்.",
    "card.upi.title": "UPI பயிற்சி",
    "card.upi.desc": "படிப்படியான வழிகாட்டுதலுடன் UPI பாதுகாப்பாக பயன்படுத்த கற்றுக்கொள்ளுங்கள்.",
    "card.scamy.title": "மோசடி சிமுலேட்டர்",
    "card.scamy.desc": "Scamy போலி மோசடியாளருடன் பேசி தந்திரங்களை எதிர்க்க கற்றுக்கொள்ளுங்கள்.",
    "card.progress.title": "குடும்பம் & ராக்கி",
    "card.progress.desc": "உங்கள் டிஜிட்டல் ராக்கி வாக்குறுதியைக் கண்டு குடும்ப நினைவுகளைத் திறக்கவும்.",
    "card.cta": "தொடங்கு",
    "hero.meet": "Meena Didi ஐ சந்தியுங்கள் — உங்கள் டிஜிட்டல் பாதுகாப்பு வழிகாட்டி!",
    "nav.quiz": "வினாடி வினா",
    "nav.sandbox": "சிமுலேட்டர்கள்",
    "nav.scamy": "Scamy",
    "nav.badges": "Badges",
    "nav.home": "முகப்பு",
    "nav.about": "எங்களை பற்றி",
    "nav.help": "உதவி",
    "settings.elderly": "மூத்தோர் முறை",
    "settings.dark": "இருண்ட பயன்முறை",
    "settings.font": "எழுத்துரு அளவு",
    "chatur.name": "சதுர்",
    "chatur.role": "உங்கள் பாதுகாப்பு உதவியாளர்",
    "chatur.greeting": "வணக்கம்! நான் சதுர் 🛡️ உங்கள் டிஜிட்டல் பாதுகாப்பு நண்பர்.",
    "chatur.placeholder": "சைபர் பாதுகாப்பு பற்றி கேளுங்கள்...",
    "chatur.listening": "கேட்கிறேன்...",
    "chatur.processing": "செயலாக்குகிறேன்...",
    "font.small": "சி",
    "font.medium": "ம",
    "font.large": "பெ",
    "font.xl": "XL",
    "trust.scams": "மோசடிகள் கண்டறியப்பட்டன",
    "trust.users": "பயனர்கள் பாதுகாக்கப்பட்டனர்",
    "trust.tips": "பாதுகாப்பு குறிப்புகள்",
    "game.title": "பாதுகாப்பா அல்லது மோசடியா?",
    "game.subtitle": "உண்மையான சூழ்நிலைகளில் உங்கள் சைபர் பாதுகாப்பு அறிவை சோதியுங்கள்",
    "game.safe": "பாதுகாப்பு ✅",
    "game.scam": "மோசடி ❌",
    "game.correct": "சரி! 👍",
    "game.wrong": "அடுத்த முறை கவனமாக இருங்கள் ⚠️",
    "game.next": "அடுத்த கேள்வி",
    "game.restart": "மீண்டும் விளையாடு",
    "game.score": "உங்கள் மதிப்பெண்",
    "game.back": "முகப்புக்கு திரும்பு",
    "game.whatToDo": "என்ன செய்ய வேண்டும்",
    "game.level": "நிலை",
    "upi.title": "UPI பாதுகாப்பு பயிற்சி",
    "upi.subtitle": "இந்த படிப்படியான வழிகாட்டியுடன் UPI பாதுகாப்பாக பயன்படுத்த கற்றுக்கொள்ளுங்கள்",
    "upi.step": "படி",
    "upi.next": "அடுத்த படி",
    "upi.prev": "முந்தைய",
    "upi.finish": "பயிற்சி முடிக்க",
    "upi.back": "முகப்புக்கு திரும்பு",
    "upi.complete": "பயிற்சி முடிந்தது! 🎉",
    "upi.completeDesc": "இப்போது நீங்கள் UPI பாதுகாப்பாக பயன்படுத்த தெரிந்துகொண்டீர்கள்.",
    "card.deepfake.title": "RealityCheck ஆய்வகம்",
    "card.deepfake.desc": "படங்கள் அல்லது ஆடியோவை ஒப்பிட்டு AI-உருவாக்கிய போலி ஆக்கங்களை கண்டறியவும்.",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
    "lang.mr": "मराठी",
    "lang.ta": "தமிழ்",
    "lang.te": "తెలుగు",
    "lang.pa": "ਪੰਜਾਬੀ",
  },
  te: {
    "app.name": "DigiRakshak",
    "app.tagline": "AI-ఆధారిత సైబర్ భద్రత",
    "hero.title1": "డిజిటల్ ప్రపంచంలో",
    "hero.title2": "సురక్షితంగా ఉండండి",
    "hero.subtitle": "DigiRakshak స్కామ్ కాల్స్, అనుమానాస్పద సందేశాలను గుర్తించడంలో మీకు సహాయపడుతుంది.",
    "card.call.title": "కాల్ తనిఖీ",
    "card.call.desc": "వచ్చిన కాల్ స్కామర్ నుండి వచ్చిందా లేదా చెల్లుబాటు అయ్యేదా తనిఖీ చేయండి.",
    "card.message.title": "సందేశం తనిఖీ",
    "card.message.desc": "అనుమానాస్పద SMS లేదా WhatsApp సందేశాన్ని పేస్ట్ చేయండి.",
    "card.game.title": "గేమ్ ద్వారా నేర్చుకోండి",
    "card.game.desc": "సరదా క్విజ్‌లు ఆడి ఆన్‌లైన్ భద్రత నేర్చుకోండి.",
    "card.sandbox.title": "భద్రతా సిమ్యులేటర్లు",
    "card.sandbox.desc": "సురక్షితమైన సిమ్యులేటెడ్ వాతావరణంలో స్కామ్‌లను గుర్తించడం సాధన చేయండి.",
    "card.upi.title": "UPI శిక్షణ",
    "card.upi.desc": "దశల వారీ మార్గదర్శకత్వంతో UPI సురక్షితంగా ఉపయోగించడం నేర్చుకోండి.",
    "card.scamy.title": "స్కామ్ సిమ్యులేటర్",
    "card.scamy.desc": "Scamy నకిలీ స్కామర్‌తో మాట్లాడండి మరియు తప్పించుకోవడం నేర్చుకోండి.",
    "card.progress.title": "కుటుంబం & రాఖీ",
    "card.progress.desc": "మీ డిజిటల్ రాఖీ హామీని చూడండి మరియు కుటుంబ జ్ఞాపకాలను అన్‌లాక్ చేయండి.",
    "card.cta": "ప్రారంభించండి",
    "hero.meet": "Meena Didi ని కలవండి — మీ డిజిటల్ భద్రతా మార్గదర్శి!",
    "nav.quiz": "క్విజ్",
    "nav.sandbox": "సిమ్యులేటర్లు",
    "nav.scamy": "Scamy",
    "nav.badges": "Badges",
    "nav.home": "హోమ్",
    "nav.about": "మా గురించి",
    "nav.help": "సహాయం",
    "settings.elderly": "వృద్ధుల మోడ్",
    "settings.dark": "డార్క్ మోడ్",
    "settings.font": "ఫాంట్ పరిమాణం",
    "chatur.name": "చతుర్",
    "chatur.role": "మీ భద్రతా సహాయకుడు",
    "chatur.greeting": "నమస్కారం! నేను చతుర్ 🛡️ మీ డిజిటల్ భద్రతా మిత్రుడు.",
    "chatur.placeholder": "సైబర్ భద్రత గురించి అడగండి...",
    "chatur.listening": "వింటున్నాను...",
    "chatur.processing": "ప్రాసెస్ చేస్తున్నాను...",
    "font.small": "చి",
    "font.medium": "మ",
    "font.large": "పె",
    "font.xl": "XL",
    "trust.scams": "స్కామ్‌లు గుర్తించబడ్డాయి",
    "trust.users": "వినియోగదారులు రక్షించబడ్డారు",
    "trust.tips": "భద్రతా చిట్కాలు",
    "game.title": "సేఫ్ లేదా స్కామ్?",
    "game.subtitle": "నిజమైన పరిస్థితులతో మీ సైబర్ భద్రతా జ్ఞానాన్ని పరీక్షించండి",
    "game.safe": "సురక్షితం ✅",
    "game.scam": "స్కామ్ ❌",
    "game.correct": "సరైనది! 👍",
    "game.wrong": "తదుపరిసారి జాగ్రత్తగా ఉండండి ⚠️",
    "game.next": "తదుపరి ప్రశ్న",
    "game.restart": "మళ్ళీ ఆడండి",
    "game.score": "మీ స్కోర్",
    "game.back": "హోమ్‌కు తిరిగి",
    "game.whatToDo": "ఏమి చేయాలి",
    "game.level": "లెవల్",
    "upi.title": "UPI భద్రతా శిక్షణ",
    "upi.subtitle": "ఈ దశల వారీ గైడ్‌తో UPI సురక్షితంగా ఉపయోగించడం నేర్చుకోండి",
    "upi.step": "దశ",
    "upi.next": "తదుపరి దశ",
    "upi.prev": "మునుపటి",
    "upi.finish": "శిక్షణ పూర్తి చేయండి",
    "upi.back": "హోమ్‌కు తిరిగి",
    "upi.complete": "శిక్షణ పూర్తయింది! 🎉",
    "upi.completeDesc": "ఇప్పుడు మీకు UPI సురక్షితంగా ఉపయోగించడం తెలుసు.",
    "card.deepfake.title": "RealityCheck ల్యాబ్",
    "card.deepfake.desc": "చిత్రాలు లేదా ఆడియోను పోల్చడం ద్వారా AI-రూపొందించిన ఆకృతులను గుర్తించండి.",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
    "lang.mr": "मराठी",
    "lang.ta": "தமிழ்",
    "lang.te": "తెలుగు",
    "lang.pa": "ਪੰਜਾਬੀ",
  },
  pa: {
    "app.name": "DigiRakshak",
    "app.tagline": "AI-ਸੰਚਾਲਿਤ ਸਾਈਬਰ ਸੁਰੱਖਿਆ",
    "hero.title1": "ਡਿਜੀਟਲ ਦੁਨੀਆ ਵਿੱਚ",
    "hero.title2": "ਸੁਰੱਖਿਅਤ ਰਹੋ",
    "hero.subtitle": "DigiRakshak ਸਕੈਮ ਕਾਲਾਂ, ਸ਼ੱਕੀ ਸੁਨੇਹਿਆਂ ਦੀ ਪਛਾਣ ਕਰਨ ਵਿੱਚ ਤੁਹਾਡੀ ਮਦਦ ਕਰਦਾ ਹੈ।",
    "card.call.title": "ਕਾਲ ਚੈੱਕ ਕਰੋ",
    "card.call.desc": "ਚੈੱਕ ਕਰੋ ਕਿ ਆਉਣ ਵਾਲੀ ਕਾਲ ਸਕੈਮਰ ਦੀ ਹੈ ਜਾਂ ਅਸਲੀ ਸਰੋਤ ਦੀ।",
    "card.message.title": "ਸੁਨੇਹਾ ਚੈੱਕ ਕਰੋ",
    "card.message.desc": "ਕੋਈ ਵੀ ਸ਼ੱਕੀ SMS ਜਾਂ WhatsApp ਸੁਨੇਹਾ ਪੇਸਟ ਕਰੋ।",
    "card.game.title": "ਗੇਮ ਨਾਲ ਸਿੱਖੋ",
    "card.game.desc": "ਮਜ਼ੇਦਾਰ ਕੁਇਜ਼ ਖੇਡ ਕੇ ਔਨਲਾਈਨ ਸੁਰੱਖਿਆ ਸਿੱਖੋ।",
    "card.sandbox.title": "ਸੁਰੱਖਿਆ ਸਿਮੂਲੇਟਰ",
    "card.sandbox.desc": "ਇੱਕ ਸੁਰੱਖਿਅਤ ਸਿਮੂਲੇਟਡ ਵਾਤਾਵਰਣ ਵਿੱਚ ਸਕੈਮ ਦੀ ਪਛਾਣ ਕਰਨ ਦਾ ਅਭਿਆਸ ਕਰੋ।",
    "card.upi.title": "UPI ਸਿਖਲਾਈ",
    "card.upi.desc": "ਕਦਮ-ਦਰ-ਕਦਮ ਮਾਰਗਦਰਸ਼ਨ ਨਾਲ UPI ਸੁਰੱਖਿਅਤ ਵਰਤਣਾ ਸਿੱਖੋ।",
    "card.scamy.title": "ਸਕੈਮ ਸਿਮੂਲੇਟਰ",
    "card.scamy.desc": "Scamy ਨਕਲੀ ਸਕੈਮਰ ਨਾਲ ਗੱਲ ਕਰੋ ਅਤੇ ਚਾਲਾਂ ਤੋਂ ਬਚਣਾ ਸਿੱਖੋ।",
    "card.progress.title": "ਪਰਿਵਾਰ ਅਤੇ ਰਾਖੀ",
    "card.progress.desc": "ਆਪਣਾ ਡਿਜੀਟਲ ਰਾਖੀ ਵਾਅਦਾ ਦੇਖੋ ਅਤੇ ਪਰਿਵਾਰਕ ਯਾਦਾਂ ਅਨਲੌਕ ਕਰੋ।",
    "card.cta": "ਸ਼ੁਰੂ ਕਰੋ",
    "hero.meet": "Meena Didi ਨੂੰ ਮਿਲੋ — ਤੁਹਾਡੀ ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ ਗਾਈਡ!",
    "nav.quiz": "ਕੁਇਜ਼",
    "nav.sandbox": "ਸਿਮੂਲੇਟਰ",
    "nav.scamy": "Scamy",
    "nav.badges": "Badges",
    "nav.home": "ਹੋਮ",
    "nav.about": "ਸਾਡੇ ਬਾਰੇ",
    "nav.help": "ਮਦਦ",
    "settings.elderly": "ਬਜ਼ੁਰਗ ਮੋਡ",
    "settings.dark": "ਡਾਰਕ ਮੋਡ",
    "settings.font": "ਫੌਂਟ ਆਕਾਰ",
    "chatur.name": "ਚਤੁਰ",
    "chatur.role": "ਤੁਹਾਡਾ ਸੁਰੱਖਿਆ ਸਹਾਇਕ",
    "chatur.greeting": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਚਤੁਰ ਹਾਂ 🛡️ ਤੁਹਾਡਾ ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ ਸਾਥੀ।",
    "chatur.placeholder": "ਸਾਈਬਰ ਸੁਰੱਖਿਆ ਬਾਰੇ ਪੁੱਛੋ...",
    "chatur.listening": "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
    "chatur.processing": "ਪ੍ਰੋਸੈਸਿੰਗ...",
    "font.small": "ਛੋ",
    "font.medium": "ਮ",
    "font.large": "ਵੱ",
    "font.xl": "XL",
    "trust.scams": "ਸਕੈਮ ਫੜੇ ਗਏ",
    "trust.users": "ਉਪਭੋਗਤਾ ਸੁਰੱਖਿਅਤ",
    "trust.tips": "ਸੁਰੱਖਿਆ ਟਿਪਸ ਸਾਂਝੀਆਂ",
    "game.title": "ਸੇਫ਼ ਜਾਂ ਸਕੈਮ?",
    "game.subtitle": "ਅਸਲ ਸਥਿਤੀਆਂ ਨਾਲ ਆਪਣੇ ਸਾਈਬਰ ਸੁਰੱਖਿਆ ਗਿਆਨ ਦੀ ਜਾਂਚ ਕਰੋ",
    "game.safe": "ਸੁਰੱਖਿਅਤ ✅",
    "game.scam": "ਸਕੈਮ ❌",
    "game.correct": "ਸਹੀ! 👍",
    "game.wrong": "ਅਗਲੀ ਵਾਰ ਸਾਵਧਾਨ ਰਹੋ ⚠️",
    "game.next": "ਅਗਲਾ ਸਵਾਲ",
    "game.restart": "ਦੁਬਾਰਾ ਖੇਡੋ",
    "game.score": "ਤੁਹਾਡਾ ਸਕੋਰ",
    "game.back": "ਹੋਮ ਤੇ ਵਾਪਸ",
    "game.whatToDo": "ਕੀ ਕਰਨਾ ਹੈ",
    "game.level": "ਲੈਵਲ",
    "upi.title": "UPI ਸੁਰੱਖਿਆ ਸਿਖਲਾਈ",
    "upi.subtitle": "ਇਸ ਕਦਮ-ਦਰ-ਕਦਮ ਗਾਈਡ ਨਾਲ UPI ਸੁਰੱਖਿਅਤ ਵਰਤਣਾ ਸਿੱਖੋ",
    "upi.step": "ਕਦਮ",
    "upi.next": "ਅਗਲਾ ਕਦਮ",
    "upi.prev": "ਪਿਛਲਾ",
    "upi.finish": "ਸਿਖਲਾਈ ਪੂਰੀ ਕਰੋ",
    "upi.back": "ਹੋਮ ਤੇ ਵਾਪਸ",
    "upi.complete": "ਸਿਖਲਾਈ ਪੂਰੀ! 🎉",
    "upi.completeDesc": "ਹੁਣ ਤੁਸੀਂ UPI ਸੁਰੱਖਿਅਤ ਵਰਤਣਾ ਜਾਣਦੇ ਹੋ। ਇਹ ਟਿਪਸ ਯਾਦ ਰੱਖੋ!",
    "card.deepfake.title": "RealityCheck ਲੈਬ",
    "card.deepfake.desc": "ਚਿੱਤਰਾਂ ਜਾਂ ਆਡੀਓ ਦੀ ਤੁਲਨਾ ਕਰਕੇ AI-ਨਿਰਮਿਤ ਨਕਲੀ ਚਿੱਤਰਾਂ ਜਾਂ ਆਵਾਜ਼ਾਂ ਦੀ ਪਛਾਣ ਕਰੋ।",
    "lang.en": "English",
    "lang.hi": "हिन्दी",
    "lang.mr": "मराठी",
    "lang.ta": "தமிழ்",
    "lang.te": "తెలుగు",
    "lang.pa": "ਪੰਜਾਬੀ",
  },
};

const AppSettingsContext = createContext<AppSettings | null>(null);

export const useAppSettings = () => {
  const ctx = useContext(AppSettingsContext);
  if (!ctx) throw new Error("useAppSettings must be used within AppSettingsProvider");
  return ctx;
};

export const AppSettingsProvider = ({ children }: { children: ReactNode }) => {
  const [darkMode, setDarkMode] = useState(false);
  const [elderlyMode, setElderlyMode] = useState(false);
  const [language, setLanguage] = useState<Language>("en");
  const [fontScale, setFontScale] = useState<FontScale>("medium");

  useEffect(() => {
    const root = document.documentElement;
    root.classList.toggle("dark", darkMode);
    root.classList.toggle("elderly", elderlyMode);

    root.classList.remove("font-scale-small", "font-scale-medium", "font-scale-large", "font-scale-xl");

    if (elderlyMode) {
      root.classList.add("font-scale-xl");
    } else {
      root.classList.add(`font-scale-${fontScale}`);
    }
  }, [darkMode, elderlyMode, fontScale]);

  const t = (key: string) => {
    const stringVal = translations[language][key] || key;
    return replaceJargon(stringVal, elderlyMode);
  };

  const simplify = (str: string) => replaceJargon(str, elderlyMode);

  return (
    <AppSettingsContext.Provider
      value={{ darkMode, elderlyMode, language, fontScale, setDarkMode, setElderlyMode, setLanguage, setFontScale, t, simplify }}
    >
      {children}
    </AppSettingsContext.Provider>
  );
};
